INSERT INTO reward_actions (action_name, immediate)
VALUES ('Build the Gates, Towers or Walls of my castle.', TRUE),
       ('Buy Patrons from the Allies and Mercenaries quadrants of the Wealth Wheel', TRUE),
       ('Build and pay all tithes in each Chapel level', FALSE),
       ('Overwhelm by 4 strength to earn an extra Patron', FALSE),
       ('Convert to soldiers (and soldier production) in the Training grounds', TRUE),
       ('Start the Warcraft Leadership row for a soldier', TRUE),
       ('Buy Soldiers from the Mercenaries quadrant of the Wealth wheel.', TRUE),
       ('Fill in the Ramparts line in the Leadership row (and Soldier production)', FALSE),
       ('Build Tactics from the Warcraft Leadership line for a soldier', FALSE),
       ('Build the Siege Tower or Trebuchet', FALSE),
       ('Create Knights at the Knight''s Training area in the Worship row', FALSE),
       ('Score bonus Soldiers', FALSE),
       ('Use Knights Training on the Worship Leadership row', FALSE),
       ('A Knight can be found on the Governance Leadership line.', FALSE),
       ('A Knight and Knight production can be found at the end of the Warcraft Leadership line', FALSE),
       ('Build Keeps in the Governance Leadership line', FALSE),
       ('Buy serfs from the Siegecraft quadrant of the Wealth wheel.', TRUE),
       ('Use the St. Valentine''s Festival area in the Worship Leadership row.', FALSE),
       ('Serfs and Serf production can be found on the Governance and Entertainment Leadership lines.', FALSE),
       ('Score bonus Serfs', FALSE),
       ('For every 3 strength remaining after resolving all attacks, gain a Serf for the next round.', FALSE),
       ('Buy knights them from the Guildsmen quadrant of the Wealth wheel (or one craftsman in the Allies quadrant). Note: There are Craftsmen production at the end of the Guildsmen ‘tree’.',
        TRUE),
       ('A Craftsman can be found in every Leadership line.', FALSE),
       ('Overwhelm by 4 strength to earn an extra Craftsman.', FALSE),
       ('Convert to Food (and Food production) at the Farms.', TRUE),
       ('Food can be found in the Worship and Entertainment Leadership lines.', FALSE),
       ('Build the Keep in the Governance Leadership line and choose Food', FALSE),
       ('Use the Michaelmas area in the Entertainment row and choose Food.', FALSE),
       ('Overwhelm by 2 strength to earn extra Food.', FALSE),
       ('Convert to Materials (and Material production) at the Quarry & Forest.', TRUE),
       ('Build the Castle Moat.', TRUE),
       ('Materials can be found on the Governance, Warcraft & Entertainment Leadership lines.', FALSE),
       ('Build the Keep in the Governance Leadership line and choose Materials.', FALSE),
       ('Use the Michaelmas area in the Entertainment row and choose Materials', FALSE),
       ('Overwhelm by 3 strength to earn extra Material.', FALSE),
       ('Silver can be found on the Governance, Worship and Entertainment Leadership lines', FALSE),
       ('Build Keeps in the Governance Leadership line and choose Silver', FALSE),
       ('Use the Michaelmas area in the Entertainment row and choose Silver.', FALSE),
       ('Overwhelm by 3 strength to earn extra Silver.', FALSE),
       ('Run Tournaments in the Entertainment row', FALSE),
       ('Score bonus Patrons', FALSE),
       ('Fill the stables', FALSE),
       ('Buy craftsmen from the Guildsmen quadrant of the Wealth wheel (or one craftsman in the Allies quadrant). Note: There are Craftsmen production at
the end of the Guildsmen ‘tree’.', TRUE);